version: 2
jobs:
  build:
    docker:
      - image: centos:7
    working_directory: ~/go/src/github.com/scholzj/amqpctl
    steps:
      - run:
          name: Install dependencies
          command: yum install -y git tar curl wget gcc
      - run:
          name: Install Go
          command: |
            curl -o /tmp/golang.tar.gz https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
            tar -C /usr/local -xzf /tmp/golang.tar.gz
            echo 'export PATH=/usr/local/go/bin:$PATH' >> $BASH_ENV
      - checkout
      - run:
          name: Install Qpid dependencies
          command: |
            curl -o /etc/yum.repos.d/qpid-proton-devel.repo http://repo.effectivemessaging.com/qpid-proton-stable.repo
            yum install -y qpid-proton-c-devel
      - run:
          name: Get dependencies
          command: go get
      - run:
          name: Build
          command: go build
      - run:
          name: Test
          command: go test