version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/scholzj/amqpctl
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo add-apt-repository ppa:qpid/testing --yes
            sudo apt-get update -q
            sudo apt-get install -q -y libqpid-proton10-dev
      - run:
          name: Get dependencies
          command: go get
      - run:
          name: Build
          command: go build
      - run:
          name: Test
          command: go test