version: 2
jobs:
  build:
    docker:
      - image: scholzj/circleci-centos-golang:centos7-1.8.3
    working_directory: ~/go/src/github.com/scholzj/amqpctl
    steps:
      - checkout
      - run:
          name: Install Qpid dependencies
          command: |
            sudo curl -o /etc/yum.repos.d/qpid-proton-devel.repo http://repo.effectivemessaging.com/qpid-proton-stable.repo
            sudo yum install -y qpid-proton-c-devel
      - run:
          name: Get dependencies
          command: go get
      - run:
          name: Build
          command: go build
      - run:
          name: Test
          command: go test